# Generated by Django 5.2.9 on 2026-01-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='title',
        ),
    ]
