# Generated by Django 5.2.9 on 2026-01-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_logs', '0002_remove_dailylog_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(help_text='Mood label like Happy, Stressed, Calm', max_length=50)),
                ('score', models.IntegerField(help_text='Mood intensity score from 1 to 10')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Date when this mood was recorded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
